### ISSUE TITLE
Migrate https://github.com/nexB/matchcode-toolkit to https://github.com/aboutcode-org/

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/matchcode-toolkit#10]

**Comment by JonoYang** [comment]
@pombredanne 

I've moved https://github.com/nexB/matchcode-toolkit to https://github.com/aboutcode-org/matchcode-toolkit using the following steps:

1. Create empty repo on aboutcode-org
2. Clone empty repo to system
3. Add previous repo as remote:
    - `git remote add old-repo git@github.com:nexB/matchcode-toolkit.git`
4. Merge old repo with new empty repo
    - `git merge old-repo/main --allow-unrelated-histories`
5. Push to github
6. Push tags to github
    - `git push --tags`
7. Recreate releases on new repo

Azure DevOps needs access to the aboutcode-org repos for CI to work.

**Comment by JonoYang** [comment]
A simpler way to achieve what I did above:

1. Transfer the nexB repo to the aboutcode-org organization from `Settings -> Danger Zone -> Transfer ownership`
2. Set up CI for that repo on Azure Devops
  - Log into the nexB organization on Azure Devops
  - Go to the project that was moved
  - On the left hand menu, click on `Pipelines`, and then delete the existing pipeline
  - On the same page, click `New pipeline`, and then click `Github`, then select the repo that was transferred to aboutcode-org
  - Complete adding the pipeline

**Comment by mjherzog** [comment]
Guessing that we should just ignore that most repos are based on the nexB skeleton.

**Comment by mjherzog** [comment]
More steps:
- Update org-level permissions
- Check org-level permissions for each repo and update repo-level permissions.
- Update URLs over time.
- Create new PyPI release with updated URLs.
So we should create an Issue template / checklist for this and create a nexB org-level project.

**Comment by pombredanne** [comment]
> Guessing that we should just ignore that most repos are based on the nexB skeleton.

Good point... we need to make a test migration with a repo template too.

**Comment by JonoYang** [comment]
This has been done. Closing.
